services:
  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    container_name: stockflow-backend
    ports:
      - "8080:8080"
    networks:
      - stockflow-net

  inventory-app:
    build:
      context: ./inventory-app
      dockerfile: Dockerfile
    container_name: stockflow-frontend
    ports:
      - "4200:80"
    depends_on:
      - inventory-service
    networks:
      - stockflow-net

networks:
  stockflow-net:
    driver: bridge
